src/CI/CoreBundle/Entity/Group.php
<?php

namespace CI\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use FOS\UserBundle\Model\Group as BaseGroup;
use CI\CoreBundle\Permissions;

/**
 * Group
 *
 * @ORM\Table(name="user_group")
 * @ORM\Entity(repositoryClass="CI\CoreBundle\Entity\GroupRepository")
 * @UniqueEntity(fields="name", message="This Role name is already in use.")
 */
class Group extends BaseGroup
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @var string
	 *
	 * @Assert\NotBlank
	 */
	protected $name;

	/**
	 * @Assert\Count(min="1", minMessage="Please select at least one (1) permission.")
	 */
	protected $roles;

	/**
	 * @ORM\ManyToMany(targetEntity="User", mappedBy="groups")
	 */
	private $users;

	public function __construct($name, $roles = array())
	{
		$this->name = $name;
		$this->roles = $roles;
		$this->users = new \Doctrine\Common\Collections\ArrayCollection();
	}

	/**
	 * Add user
	 *
	 * @param \CI\CoreBundle\Entity\User $user
	 *
	 * @return Group
	 */
	public function addUser(\CI\CoreBundle\Entity\User $user)
	{
		$this->users[] = $user;

		return $this;
	}

	/**
	 * Remove user
	 *
	 * @param \CI\CoreBundle\Entity\User $user
	 */
	public function removeUser(\CI\CoreBundle\Entity\User $user)
	{
		$this->users->removeElement($user);
	}

	/**
	 * Get users
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getUsers()
	{
		return $this->users;
	}

	public function getTranslatedPermissions()
	{
		return array_map(function($role) {
			return Permissions::getPermissions()[$role];
		}, $this->getRoles());
	}

	public function isDeletable()
	{
		if ($this->getUsers()->count() == 0) {
			return true;
		}

		return false;
	}
}

src/CI/CoreBundle/Form/Type/GroupType.php
<?php

namespace CI\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use CI\CoreBundle\Permissions;

class GroupType extends AbstractType
{
	/**
	 * @param FormBuilderInterface $builder
	 * @param array $options
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('name')
			->add('roles', 'choice', array(
				'label' => 'Permissions',
				'multiple' => true,
				'expanded' => true,
				'choices' => Permissions::getPermissions(),
			))
		;
	}
	
	/**
	 * @param OptionsResolverInterface $resolver
	 */
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'CI\CoreBundle\Entity\Group'
		));
	}
	
	/**
	 * @return string
	 */
	public function getName()
	{
		return 'ci_corebundle_group';
	}
}

src/CI/CoreBundle/Controller/GroupController.php
<?php

namespace CI\CoreBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use JMS\SecurityExtraBundle\Annotation\PreAuthorize;

use CI\CoreBundle\Entity\Group;
use CI\CoreBundle\Form\Type\GroupFilterType;
use CI\CoreBundle\Form\Type\GroupType;
use CI\InventoryBundle\Controller\BaseController;

/**
 * Group controller.
 */
class GroupController extends BaseController
{
	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function listAction(Request $request)
	{
		$em = $this->getDoctrine()->getManager();
		$form = $this->createForm(new GroupFilterType());
		
		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				$params = $form->getData();
				$qb = $em->getRepository('CICoreBundle:Group')->findAll($params);
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please try again.');
			}
		}

		if (!isset($qb)) {
			$qb = $em->getRepository('CICoreBundle:Group')->findAll();
		}

		$paginator = $this->get('knp_paginator');
			$pagination = $paginator->paginate(
			$qb,
			$this->get('request')->query->get('page', 1),
			$this->container->getParameter('pagination_limit_per_page')
		);
		
		return $this->render('CICoreBundle:Group:index.html.twig', array(
			'pagination' => isset($pagination) ? $pagination : null,
			'search_form' => $form->createView(),
		));
	}

	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function createAction(Request $request)
	{
		$entity = new Group('', array());
		$form = $this->createForm(new GroupType, $entity);
		
		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				$em = $this->getDoctrine()->getManager();
				$em->persist($entity);
				$em->flush();
				
				$this->get('session')->getFlashBag()->add('success', 'Role has been successfully created.');
				
				return $this->redirect($this->generateUrl('fos_user_group_show', array('id' => $entity->getId())));
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
			}
		}
		
		return $this->render('CICoreBundle:Group:new.html.twig', array(
			'entity' => $entity,
			'form'   => $form->createView(),
			'angular' => true,
		));
	}
	
	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function newAction()
	{
		$entity = new Group('', array());
		$form = $this->createForm(new GroupType, $entity);
		
		return $this->render('CICoreBundle:Group:new.html.twig', array(
			'entity' => $entity,
			'form'   => $form->createView(),
			'angular' => true,
		));
	}

	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function showAction($id)
	{
		$em = $this->getDoctrine()->getManager();

		$entity = $em->getRepository('CICoreBundle:Group')->find($id);
		
		return $this->render('CICoreBundle:Group:show.html.twig', array(
			'entity' => $entity,
		));
	}

	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function editAction($id)
	{
		$em = $this->getDoctrine()->getManager();
		$entity = $em->getRepository('CICoreBundle:Group')->find($id);
		$editForm = $this->createForm(new GroupType, $entity, array('method' => 'PUT'));
		
		return $this->render('CICoreBundle:Group:edit.html.twig', array(
			'entity' => $entity,
			'edit_form' => $editForm->createView(),
			'angular' => true,
		));
	}

	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function updateAction(Request $request, $id)
	{
		$em = $this->getDoctrine()->getManager();
		$entity = $em->getRepository('CICoreBundle:Group')->find($id);
		$editForm = $this->createForm(new GroupType, $entity, array('method' => 'PUT'));
		
		if ($editForm->handleRequest($request)->isSubmitted()) {
			if ($editForm->isValid()) {
				$em->persist($entity);
				$em->flush();
				
				$this->get('session')->getFlashBag()->add('success', 'Role has successfully been updated.');
				
				return $this->redirect($this->generateUrl('fos_user_group_show', array('id' => $id)));
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
			}
		}
		
		return $this->render('CICoreBundle:Group:edit.html.twig', array(
			'entity' => $entity,
			'edit_form' => $editForm->createView(),
			'angular' => true,
		));
	}
	
	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function confirmDeleteAction($id)
	{
		$em = $this->getDoctrine()->getManager();
		$entity = $em->getRepository('CICoreBundle:Group')->find($id);
		$deleteForm = $this->createDeleteForm($id);

		if ($entity->isDeletable() === false) {
			$this->get('session')->getFlashBag()->add('danger', 'This role has already been added to a user, therefore can no longer be deleted.');
			return $this->redirect($this->generateUrl('fos_user_group_show', array('id' => $id)));
		}

		$params = array(
			'path' => 'fos_user_group_delete',
			'return_path' => 'fos_user_group_show',
			'name' => '[Role] ' . $entity->getName() . ' (ID #' . $entity->getId() . ')',
		);

		return $this->render('CIInventoryBundle:Misc:delete.html.twig', array(
			'params' => $params,
			'entity' => $entity,
			'delete_form' => $deleteForm->createView(),
		));
	}
	
	/**
	 * @PreAuthorize("hasRole('ROLE_ADMIN')")
	 */
	public function deleteAction(Request $request, $id)
	{
		$em = $this->getDoctrine()->getManager();
		$entity = $em->getRepository('CICoreBundle:Group')->find($id);
		$deleteForm = $this->createDeleteForm($id);
		$deleteForm->handleRequest($request);
	
		if ($entity->isDeletable() === false) {
			$this->get('session')->getFlashBag()->add('danger', 'This role has already been added to a user, therefore can no longer be deleted.');
			return $this->redirect($this->generateUrl('fos_user_group_show', array('id' => $id)));
		}
	
		if ($deleteForm->isValid()) {
			try {
				$em->remove($entity);
				$em->flush();
	
				$this->get('session')->getFlashBag()->add('success', 'Role has been deleted.');
				return $this->redirect($this->generateUrl('fos_user_group_list'));
			} catch (\Exception $e) {
				$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
			}
		} else {
			$this->get('session')->getFlashBag()->add('danger', 'Oops! Unknown error occured. Please try again.');
		}
	
		$params = array(
			'path' => 'fos_user_group_delete',
			'return_path' => 'fos_user_group_show',
			'name' => '[Role] ' . $entity->getName() . ' (ID #' . $entity->getId() . ')',
		);
	
		return $this->render('CIInventoryBundle:Misc:delete.html.twig', array(
			'params' => $params,
			'entity' => $entity,
			'delete_form' => $deleteForm->createView(),
		));
	}
}

src/CI/CoreBundle/Resources/views/Group/edit.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CICoreBundle:Group:macro.html.twig' as macro %}

{% block breadcrumbs %}
<li>Settings</li>
<li><a href="{{ path('fos_user_group_list') }}">Roles</a></li>
<li><a href="{{ path('fos_user_group_show', { 'id' : entity.id }) }}">{{ entity.name }}</a></li>
<li class="active"><a href="{{ path('fos_user_group_edit', { 'id' : entity.id }) }}">Edit</a></li>
{% endblock %}

{% block content %}
<div class="page-header">
	<small>Role ID #{{ entity.id }}</small>
	<br/>
	<h1>{{ entity.name }}</h1>
</div>


{{ form_start(edit_form, {'action': path('fos_user_group_update', { 'id' : entity.id }), 'method': 'PUT', 'attr': { 'class': 'form-horizontal', 'novalidate' : 'novalidate' } }) }}
	{{ bootstrap_set_style('horizontal') }}
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-6">
					{{ form_row(edit_form.name) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h3 class="text-center">Set Permissions</h3>
					{{ form_errors(edit_form.roles) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Accounts</h3>
					<div class="row">
						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Supplier', 0, 7) }}
        				</div>
        				<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Customer', 8, 15) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Inventory</h3>
					<div class="row">
						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Product', 16, 24) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Purchasing</h3>
					<div class="row">
						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Purchase Order', 25, 35) }}
        					{{ macro.role(edit_form.roles, 'Receive Order', 36, 43) }}
        				</div>
        				<div class="col-md-6">
        				    {{ macro.role(edit_form.roles, 'Put Away', 44, 49) }}
        				    {{ macro.role(edit_form.roles, 'Shipment Discrepancy Notice', 50, 58) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Sales</h3>
					<div class="row">
						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Quotation', 59, 70) }}
        					{{ macro.role(edit_form.roles, 'Sales Order', 71, 83) }}
        					{{ macro.role(edit_form.roles, 'Delivery', 84, 95) }}
        					{{ macro.role(edit_form.roles, 'Order Picking', 96, 100) }}
        				</div>
        				<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Backload', 101, 106) }}
        					{{ macro.role(edit_form.roles, 'Sales Return', 107, 114) }}
        					{{ macro.role(edit_form.roles, 'Sales Forecast', 115, 121) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Reports</h3>
					<div class="row">
						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Reports', 122, 138, false) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Settings</h3>
					<div class="row">

						<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Category', 139, 144) }}
        					{{ macro.role(edit_form.roles, 'Packaging', 145, 150) }}
        					{{ macro.role(edit_form.roles, 'Currency', 151, 156) }}
        				</div>
        				<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Industry', 157, 162) }}
        					{{ macro.role(edit_form.roles, 'Warehouse', 163, 167) }}
        					{{ macro.role(edit_form.roles, 'Storage Location', 168, 172) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-10 col-md-offset-1 well">
					<h3>Miscellaneous</h3>
					<div class="row">
						<div class="col-md-6">
        				    {{ macro.role(edit_form.roles, 'Sales Activity', 173, 180) }}
        				</div>
        				<div class="col-md-6">
        					{{ macro.role(edit_form.roles, 'Dashboard', 181, 184, false) }}
        				</div>
					</div>
				</div>
			</div>

			<div class="form-group form-actions">
				<div class="col-lg-12">
					<button type="submit" class="btn btn-success submit-button" data-loading-text="Saving...">Save</button>
					<a href="{{ path('fos_user_group_list') }}" class="btn btn-outline">Back</a>
				</div>
			</div>

		</div>
	</div>
{{ form_end(edit_form) }}
{% endblock %}

{% block javascripts %}
	<script>
		$('.switcher-square').switcher({
			theme: 'square',
			on_state_content: '<span class="fa fa-check"></span>',
			off_state_content: '<span class="fa fa-times"></span>'
		});

		$('.switcher-square').click(function() {
			var checkbox = $(this).parent().parent().parent();
			var container = $(this).parent().parent();

			if (!container.hasClass('no-auto-toggle') && $(this).is(':checked')) {
				if ($(this).val().indexOf("READ") == -1 && $(this).val().indexOf("LIST") == -1) {
					checkbox.find("[value*='READ']").switcher('on');
					checkbox.find("[value*='LIST']").switcher('on');
				} else if ($(this).val().indexOf("READ") > -1) {
					checkbox.find("[value*='LIST']").switcher('on');
				} else if ($(this).val().indexOf("LIST") > -1) {
					checkbox.find("[value*='READ']").switcher('on');
				}
			}
		});
	</script>
{% endblock %}

src/CI/CoreBundle/Resources/views/Group/index.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}

{% block breadcrumbs %}
<li>Settings</li>
<li class="active"><a href="{{ path('fos_user_group_list') }}">Roles</a></li>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<div class="row">
				<div class="col-xs-6 col-sm-6">
				<h1>{{ FAIcon('users') }} Roles</h1>
				</div>
				<div class="col-xs-6 col-sm-4 col-sm-offset-2">
					<div class="pull-right">
						<a class="btn btn-success btn-labeled btn-sm" href="{{ path('fos_user_group_new') }}">{{ FAIcon('plus', 'btn-label') }} Add New</a>
						<a class="btn btn-default btn-labeled btn-sm" href="{{ path('fos_user_group_list') }}">{{ FAIcon('th-large', 'btn-label') }} List All</a> 
					</div>
				</div>
			</div>
		</div>

		<div class="row search-filters">
			{{ form_start(search_form, { 'action': path('fos_user_group_list'), 'method': 'GET', 'attr': { 'class': 'form-horizontal' } }) }}
				{{ bootstrap_set_style('horizontal') }}
				
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-5">
							{{ form_row(search_form.name) }}
						</div>
						<div class="col-md-6">
							<button type="submit" class="btn btn-outline submit-button" data-loading-text="Searching...">Search</button>
						</div>
					</div>
				</div>
				
			{{ form_end(search_form) }}
		</div>
		
		{% if pagination.getPaginationData['totalCount'] > 0 %}
			 <div id="display-count" class="pull-right">
				 {{ macros.paginationCount(pagination) }}
			</div>

			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
					<tr>
						<th class="col-md-1">Action</th>
						<th class="col-md-10">{% if pagination.isSorted('g.name') %}<em>{% endif %}{{ knp_pagination_sortable(pagination, 'Name', 'c.name') }}{% if pagination.isSorted('c.name') %}</em>{%  endif %}</th>
					</tr>
					</thead>
					<tbody>
						{% for entity in pagination %}
						<tr>
							<td class="actions">
								<div class="btn-group btn-group-sm">
									<button  type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">{{ FAIcon('cog') }}</button>
									<ul class="dropdown-menu">
										<li><a href="{{ path('fos_user_group_show', { 'id' :entity.id }) }}">{{ FAIcon('search-plus') }} View</a></li>
										<li><a href="{{ path('fos_user_group_edit', { 'id' : entity.id }) }}">{{ FAIcon('pencil') }} Edit</a></li>
									</ul>
								</div>
							</td>
							<td><a href="{{ path('fos_user_group_show', { 'id' : entity.id }) }}">{{ entity.name }}</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="pull-right">
			{{ knp_pagination_render(pagination) }}
			</div>	
		{% else %}
			<div class="alert">
				No results found.
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('assets/js/index.js') }}"></script>
{% endblock %}

src/CI/CoreBundle/Resources/views/Group/macro.html.twig
{% macro role(form, label, firstIndex, lastIndex, isAutoToggle = true) %}
	<div class="form-group row">
		<label class="control-label col-lg-4 required">{{ label }}</label>
		<div class="col-lg-8">
			{% for key, role in form %}
				{% if key >= firstIndex and key <= lastIndex %}
					<div class="checkbox{% if isAutoToggle != true %} no-auto-toggle{% endif %}">
						{{ form_widget(role, { 'attr' : { 'class' : 'switcher-square' } }) }}
						<span class="lbl checkbox-label-align">{{ role.vars.label }}</span>
					</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
{% endmacro %}

src/CI/CoreBundle/Resources/views/Group/show.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}

{% block breadcrumbs %}
<li>Settings</li>
<li><a href="{{ path('fos_user_group_list') }}">Roles</a></li>
<li class="active"><a href="{{ path('fos_user_group_show', { 'id' : entity.id }) }}">{{ entity.name }}</a></li>
{% endblock %}

{% block content %}
<div class="page-header">
	<div class="btn-group pull-right">
		<a class="btn btn-primary" href="{{ path('fos_user_group_edit', { 'id': entity.id }) }}">{{ FAIcon('pencil', 'btn-label') }} Edit</a>
		<button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
			<li><a href="{{ path('fos_user_group_edit', { 'id': entity.id }) }}">{{ icon('edit') }} Edit</a></li>
			{% if entity.isDeletable %}
				<li class="divider"></li>
				<li><a href="{{ path('fos_user_group_confirm_delete', { 'id': entity.id }) }}">{{ icon('trash') }} Delete</a></li>
			{% endif %}
		</ul>
	</div>
	<small>Role ID #{{ entity.id }}</small>
	<br/>
	<h1>{{ entity.name }}</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<table class="table table-no-border profile">
			<tbody>
				<tr>
					<th class="col-md-5">Name</th>
					<td>{{ entity.name }}</td>
				</tr>
				 <tr>
					<th>Permissions</th>
					<td>
						{% for role in entity.translatedPermissions %}
							{{ role }}
							{% if not loop.last %}
								<br/>
							{% endif %}
						{% endfor %}
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<br/>

<div class="row">
	<div class="col-md-10">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#users" data-toggle="tab">Assigned Users</a></li>
		</ul>
		<div class="tab-content">
			<div id="users" class="tab-pane fade active in">
				{% if entity.users|length > 0 %}
					<div class="table-responsive">
						<table class="table table-light table-striped single-table-collection">
							<thead>
								<tr>
									<th class="col-sm-6">Username</th>
									<th class="col-sm-6">Full Name</th>
								</tr>
							</thead>
							<tbody>
								{% for user in entity.users %}
									{% if not user.expired %}
									<tr>
										<td> 
											{% if is_expr_granted("hasRole('ROLE_ADMIN')") %}
												<a href="{{ path('user_show', { 'id' : user.id }) }}">
											{% endif %}
											{{ user.username }}
											{% if is_expr_granted("hasRole('ROLE_ADMIN')") %}
												</a>
											{% endif %}
										</td>
										<td>{{ user.name }}</td>
									</tr>
									{% endif %}
								{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<div class="alert">
						No users assigned.
					</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}