src/CI/InventoryBundle/Entity/File.php
<?php

namespace CI\InventoryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * CI\InventoryBundle\Entity\File
 *
 * @ORM\Table(name="file")
 * @ORM\Entity(repositoryClass="CI\InventoryBundle\Entity\FileRepository")
 * @ORM\HasLifecycleCallbacks
 */
class File
{
	const BASE_UPLOAD_DIR = 'uploads';
	
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\Column(name="hash_name", type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $hashName;
    
    /**
     * @ORM\Column(name="file_name", type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $fileName;
    
    /**
     * @ORM\Column(name="rel_path", type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $relPath;
    
    /**
     * @ORM\Column(name="class", type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $class;
    
    /**
     * @ORM\Column(name="class_id", type="string", length=255)
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $classID;
    
    /**
     * @Assert\File(maxSize="10M")
     */
    private $file;
    
    //private $prevAbsoluteFilePath;
    
 	public function getAbsoluteFilePath()
    {
    	return empty($this->hashName) ? null : $this->getUploadRootDir() . $this->hashName . '.' . $this->getExtension();
    }
    
    public function getWebFilePath()
    {
    	return empty($this->hashName) ? null : $this->getUploadDir() . $this->hashName . '.' . $this->getExtension();
    }
    
    public function getUploadRootDir()
    {
    	return __DIR__.'/../../../../web/' . $this->getUploadDir();
    }
    
    protected function getUploadDir()
    {
    	return self::BASE_UPLOAD_DIR . '/' . $this->relPath . '/';
    }
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
    	return $this->id;
    }
    
    /**
     * Set hashName
     *
     * @param string $hashName
     * @return File
     */
    public function setHashName($hashName)
    {
    	$this->hashName = $hashName;
    
    	return $this;
    }
    
    /**
     * Get hashName
     *
     * @return string
     */
    public function getHashName()
    {
    	return $this->hashName;
    }
    
    /**
     * Set fileName
     *
     * @param string $fileName
     * @return File
     */
    public function setFileName($fileName)
    {
    	$this->fileName = $fileName;
    
    	return $this;
    }
    
    /**
     * Get fileName
     *
     * @return string
     */
    public function getFileName()
    {
    	return $this->fileName;
    }
    
    /**
     * Set relPath
     *
     * @param string $relPath
     * @return File
     */
    public function setRelPath($relPath)
    {
    	$this->relPath = $relPath;
    
    	return $this;
    }
    
    /**
     * Get relPath
     *
     * @return string
     */
    public function getRelPath()
    {
    	return $this->relPath;
    }
    
    public function setFile($file)
    {
    	$this->file = $file;
    
    	return $this;
    }
    
    public function getFile()
    {
    	return $this->file;
    }
    
    /**
     * Set class
     *
     * @param string $class
     * @return File
     */
    public function setClass($class)
    {
    	$this->class = $class;
    
    	return $this;
    }
    
    /**
     * Get class
     *
     * @return string
     */
    public function getClass()
    {
    	return $this->class;
    }
    
    /**
     * Set classID
     *
     * @param string $classID
     * @return File
     */
    public function setClassID($classID)
    {
    	$this->classID = $classID;
    
    	return $this;
    }
    
    /**
     * Get classID
     *
     * @return string
     */
    public function getClassID()
    {
    	return $this->classID;
    }
    
    public function getExtension()
    {
    	$ext = explode('.', $this->getFileName());
    	$ext = $ext[count($ext)-1];
    
    	return $ext;
    }
    
//     public function preUpload($deleteImage)
//     {
//     	if (!is_null($this->file)) {
//     		$this->prevAbsoluteFilePath = $this->getAbsoluteFilePath();
    		
//     		$hash = uniqid("", true);
//     		$this->fileName = $this->file->getClientOriginalName();
//     		$this->hashName = $hash;
//     	} elseif ($deleteImage) {
// 			// store the old absolute image path to delete after the update
// 			$this->prevAbsoluteFilePath = $this->getAbsoluteFilePath();
// 			// clear the image
// 			$this->fileName = null;
// 			$this->hashName = null;
// 		}
//     }
    
//     public function upload($deleteImage)
//     {
//     	// the file property can be empty if the field is not required
//     	if (!is_null($this->file)) {
//     		$this->file->move($this->getUploadRootDir(), $this->hashName . '.' . $this->getExtension());
//     		if (isset($this->prevAbsoluteFilePath) && file_exists($this->prevAbsoluteFilePath)) {
//     			unlink($this->prevAbsoluteFilePath);
//     		}
//     		$this->file = null;
//     	} else if ($deleteImage) {
// 			// delete previously uploaded image if exists
// 			if (isset($this->prevAbsoluteFilePath) && file_exists($this->prevAbsoluteFilePath)) {
// 				unlink($this->prevAbsoluteFilePath);
// 			}
// 		} 
//     }
    
    /**
     * @ORM\PostRemove
     */
    public function removeUpload()
    {
    	$file = $this->getAbsoluteFilePath();
    	
    	if (file_exists($file)) {
    		unlink($file);
    	}
    }
    
//     public function clearData()
//     {
//     	$this->fileName = null;
//     	$this->hashName = null;
//     }
    
//     /**
//      * Set class
//      *
//      * @param string $class
//      * @return File
//      */
//     public function setPrev($class)
//     {
//     	$this->prevAbsoluteFilePath = $class;
    
//     	return $this;
//     }
    
//     /**
//      * Get class
//      *
//      * @return string
//      */
//     public function getPrev()
//     {
//     	return $this->prevAbsoluteFilePath;
//     }
}

src/CI/InventoryBundle/Entity/PutAway.php
<?php

namespace CI\InventoryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use CI\InventoryBundle\DependencyInjection\InventoryServiceEntityInterface;
use Symfony\Component\Validator\ExecutionContextInterface;
use Doctrine\Common\Collections\Criteria;

/**
 * PutAway
 *
 * @ORM\Table(name="put_away")
 * @ORM\Entity(repositoryClass="CI\InventoryBundle\Entity\PutAwayRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Assert\Callback(methods={"validateItems"})
 */
class PutAway extends BaseEntity implements InventoryServiceEntityInterface
{
	const TYPE_RECEIVE_ORDER = 'RO';
	const TYPE_BACKLOAD = 'BL';

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="put_away_type", type="string", length=2)
	 * @Assert\Choice(choices = {"RO", "BL"})
	 */
	private $putAwayType;

	/**
	 * @ORM\ManyToOne(targetEntity="ReceiveOrder", inversedBy="putAways")
	 */
	private $receiveOrder;

	/**
	 * @ORM\ManyToOne(targetEntity="Backload", inversedBy="putAways")
	 */
	private $backload;

	/**
	 * @var date
	 *
	 * @ORM\Column(name="date", type="date")
	 * @Assert\NotBlank(message="Put Away Date must not be blank.")
	 * @Assert\Date()
	 */
	private $date;
	
	/**
	 * @ORM\OneToMany(targetEntity="PutAwayItem", mappedBy="putAway", cascade={"persist", "remove"})
	 * @Assert\Count(min="1", minMessage="You must check at least one item.")
	 * @Assert\Valid
	 */
	private $items;
	
	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->items = new \Doctrine\Common\Collections\ArrayCollection();
	}

	/**
	 * Get items
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getItems()
	{
		return $this->items;
	}
	
	/**
	 * Add items
	 *
	 * @param \CI\InventoryBundle\Entity\PutAwayItem $items
	 * @return PutAway
	 */
	public function addItem(\CI\InventoryBundle\Entity\PutAwayItem $items)
	{
		$items->setPutAway($this);
		$this->items[] = $items;
	
		return $this;
	}
	
	/**
	 * Remove items
	 *
	 * @param \CI\InventoryBundle\Entity\PutAwayItem $items
	 */
	public function removeItem(\CI\InventoryBundle\Entity\PutAwayItem $items)
	{
		$this->items->removeElement($items);
	}

	/**
	 * Set receiveOrder
	 *
	 * @param \CI\InventoryBundle\Entity\ReceiveOrder $receiveOrder
	 * @return PutAway
	 */
	public function setReceiveOrder(\CI\InventoryBundle\Entity\ReceiveOrder $receiveOrder = null)
	{
		$this->receiveOrder = $receiveOrder;
	
		return $this;
	}

	/**
	 * Get receiveOrder
	 *
	 * @return \CI\InventoryBundle\Entity\ReceiveOrder 
	 */
	public function getReceiveOrder()
	{
		return $this->receiveOrder;
	}
	
	/**
	 * Set date
	 *
	 * @param \DateTime $date
	 * @return PutAway
	 */
	public function setDate($date)
	{
		$this->date = $date;
	
		return $this;
	}

	/**
	 * Get date
	 *
	 * @return \DateTime 
	 */
	public function getDate()
	{
		return $this->date;
	}

	/**
	 * Set putAwayType
	 *
	 * @param string $putAwayType
	 * @return PutAway
	 */
	public function setPutAwayType($putAwayType)
	{
		$this->putAwayType = $putAwayType;
	
		return $this;
	}

	/**
	 * Get putAwayType
	 *
	 * @return string 
	 */
	public function getPutAwayType()
	{
		return $this->putAwayType;
	}

	/**
	 * Set backload
	 *
	 * @param \CI\InventoryBundle\Entity\Backload $backload
	 * @return PutAway
	 */
	public function setBackload(\CI\InventoryBundle\Entity\Backload $backload = null)
	{
		$this->backload = $backload;
	
		return $this;
	}

	/**
	 * Get backload
	 *
	 * @return \CI\InventoryBundle\Entity\Backload 
	 */
	public function getBackload()
	{
		return $this->backload;
	}
	
	public function isEditable()
	{
		if ($this->getPutAwayType() === self::TYPE_RECEIVE_ORDER) {
			if ($this->getReceiveOrder()->getActive() && $this->getActive()) {
				return true;
			}
		} else {
			if ($this->getBackload()->getActive() && $this->getActive()) {
				return true;
			}
		}

		return false;
	}
	
	
	public function translateStatus()
	{
		return $this->getActive() ? 'Successfully Put Away' : 'Void';
	}

	public function getStatus()
	{
		return $this->translateStatus();
	}
	
	public function getISItems()
	{
		return $this->getItems();
	}

	public function getPurchaseOrder()
	{
		return $this->getReceiveOrder()->getPurchaseOrder();
	}

	public function getWarehouse()
	{
		if ($this->getPutAwayType() === self::TYPE_RECEIVE_ORDER) {
			return $this->getPurchaseOrder()->getWarehouse();
		} else {
			return $this->getBackload()->getShipping()->getSalesOrder()->getWarehouse();
		}
	}

	public function getQtyPutAway()
	{
		$quantity = 0;
		foreach($this->getItems() as $item) {
			$quantity += $item->getQuantity();
		}
	
		return $quantity;
	}

	public function getProductsPreview() {
		$arr = array();
		foreach($this->getItems() as $item) {
			$exp = '['.$item->getProduct()->getSku() . '] ' . $item->getProduct()->getName();
			if (!in_array($exp, $arr)) {
				$arr[] = $exp;
			}
		}

		return implode("\n", $arr);
	}
	
	public function validateItems(ExecutionContextInterface $context)
	{
		foreach ($this->getItems() as $item) {
			if ($item->getIsIncluded()) {
				return true;
			}
		}
		
		// validate if at least one item was added
		$context->addViolationAt('items', 'At least one item must be put away.');
	}

	public function getLog()
	{
		return array(
			'RO #' => $this->getReceiveOrder()->getId(),
			'Date' => $this->getDate(),
			'Status' => $this->translateStatus()
		);
	}
}

src/CI/InventoryBundle/Form/Type/ReceiveOrderType.php
<?php

namespace CI\InventoryBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ReceiveOrderType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
		->add('purchaseOrder', 'entity_hidden', array(
			'class' => 'CIInventoryBundle:PurchaseOrder',
			'label' => 'PO #',
			'required' => true
		))
		->add('referenceNumber', 'text', array(
			'label' => 'Reference #',
			'required' => false,
			'attr' => array('widget_col' => 5) 
		))
		->add('dateReceived', 'date', array(
			'label'    => 'Date Received',
			'widget'   => 'single_text',
			'format'   => 'MM/dd/y',
			'attr'	   => array(
				'widget_col' => 5,
				'datepicker' => true,
				'input_group' => array('append' => 'calendar')
			)
		))
		->add('memo', 'textarea', array(
			'required' => false,
			'attr' => array('rows' => 4)
		))
		->add('items', 'collection', array(
			'type' => new ReceiveOrderItemType(),
			'allow_add' => true,
			'allow_delete' => true,
			'by_reference' => false,
			'error_bubbling' => false,
			'prototype_name' => 'ANGLR_key_ANGLR'
		))
		->add('receivedFrom', 'text', array(
			'label' => 'Received From',
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('drNo', 'text', array(
			'label' => 'DR #',
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('soNo', 'text', array(
			'label' => 'SO #',
			'required' => false,
			'attr' => array('widget_col' => 5) 
		))
		->add('invoiceNumber', 'text', array(
			'label' => 'Invoice #',
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('containerNumber', 'text', array(
			'label' => 'Container #',
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('sealNumber', 'text', array(
			'label' => 'Seal #',
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('factoryNumber', 'text', array(
			'label' => 'Factory #',
			'required' => false,
			'attr' => array('widget_col' => 5) 
		))
		->add('supplierName', 'hidden', array(
			'required' => true,
			'attr' => array('widget_col' => 5) 
		))
		->add('save', 'submit', array(
			'label' => 'Save',
			'attr' => array(
				'class' => 'btn btn-success submit-button',
				'data-loading-text' => "Saving..."
			)
		))
		;
	}
	
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'CI\InventoryBundle\Entity\ReceiveOrder'
		));
	}
	
	public function getName()
	{
		return 'ci_inventorybundle_receiveorder';
	}
}

src/CI/InventoryBundle/Resources/views/ReceiveOrder/show.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}

{% block breadcrumbs %}
<li>Purchasing</li>
<li><a href="{{ path('receiveorder') }}">Receive Orders</a></li>
<li class="active">View</li>
{% endblock breadcrumbs %}

{% block content %}
{% if entity.putAways|length > 0 %}
	{% set hasPutAway = true %}
{% else %}
	{% set hasPutAway = false %}
{% endif %}
<div class="page-header">
	<div class="row">
		<div class="col-sm-7">
			<h1>{{ FAIcon('plus-square', 'page-header-icon') }} Receive Order # {{ entity.id }}</h1>
			{{ entity|renderStatusTag }}
		</div>

		<div class="col-sm-5">
			<div class="pull-right btn-toolbar">
				<div class="btn-group">
					{% if entity.active %}
						{% if entity.purchaseOrder.status == constant('CI\\InventoryBundle\\Entity\\PurchaseOrder::STATUS_APPROVED') and entity.activePurchaseReturns|length == 0 %}
							{% if is_expr_granted("hasAnyRole('ROLE_RECEIVEDORDER_CHANGE_STATUS')") %}
								<a class="btn btn-outline btn-danger" href="{{ path("receiveorder_change_status", {'id':entity.id, 'status':constant('CI\\InventoryBundle\\Entity\\ReceiveOrder::STATUS_INACTIVE')}) }}">{{ FAIcon('warning') }} Void</a>
							{% endif %}
						{% endif %}
					{% else %}
						<a class="btn btn-outline btn-default disabled" href="#">{{ FAIcon('ban') }} Voided</a>
					{% endif %}
				</div>

				<div class="btn-group btn-group-md">
					{% if entity.isEditable and is_expr_granted("hasAnyRole('ROLE_RECEIVEORDER_UPDATE')") %}
						<a href="{{ path('receiveorder_edit', { 'id': entity.id }) }}" class="btn btn-default">{{ FAIcon('pencil') }} Edit</a>
					{% endif %}
					<a href="{{ path('receiveorder_export', { 'id': entity.id }) }}" class="btn btn-default">{{ FAIcon('print') }} Print</a>
					<div class="btn-group">
						<a href="#" class="btn dropdown-toggle" data-toggle="dropdown">More {{ FAIcon('caret-down') }}</a>
						<ul class="dropdown-menu">
							<li><a href="{{ path('receiveorder_revision', { 'id': entity.id }) }}">{{ FAIcon('info-circle') }} View Logs</a></li>
						</ul>
					</div>
				</div>

				<div class="btn-group btn-group-md">
					<a class="btn btn-default" href="{{ path('receiveorder') }}">{{ FAIcon('th-large') }} List All</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-9">
		<div class="row">
			<div class="col-md-6 col-xs-12">
				<table class="table table-no-border profile">
					<tr>
						<th class="col-md-4">PO #</th>
						<td><a href="{{ path('purchaseorder_show', { 'id' : entity.purchaseOrder.id }) }}">{{ entity.purchaseOrder.poId }}</a></td>
					</tr>
					<tr>
						<th>Received From</th>
						<td>{{ entity.receivedFrom }}</td>
					</tr>
					<tr>
						<th>Supplier Name</th>
						<td>{{ entity.supplierName }}</td>
					</tr>
					<tr>
						<th>DR #</th>
						<td>{{ entity.drNo }}</td>
					</tr>
					<tr>
						<th>Invoice #</th>
						<td>{{ entity.invoiceNumber }}</td>
					</tr>
					<tr>
						<th>SO No.</th>
						<td>{{ entity.soNo|default('') }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-6 col-xs-12">
				<table class="table table-no-border profile">
					<tr>
						<th>Date Received</th>
						<td>{{ utils.formatDate(entity.dateReceived) }}</td>
					</tr>
					<tr>
						<th class="col-md-4">Container #</th>
						<td>{{ entity.containerNumber }}</td>
					</tr>
					<tr>
						<th class="col-md-4">Seal #</th>
						<td>{{ entity.sealNumber }}</td>
					</tr>
					<tr>
						<th class="col-md-4">Factory #</th>
						<td>{{ entity.factoryNumber|default('') }}</td>
					</tr>
					<tr>
						<th>Reference #</th>
						<td>{{ entity.referenceNumber }}</td>
					</tr>
				</table>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-light">
						<thead>
							<tr>
								<th class="col-md-1 text-right">Quantity</th>
								<th class="col-md-1 text-right">Total Received</th>
								<th class="col-md-1 text-right">Balance</th>
								<th class="col-md-1">Mode</th>
								<th class="col-md-1">Type</th>
								<th class="col-md-1">Barcode</th>
								<th class="col-md-2">Product</th>
								<th class="col-md-1">Lot No.</th>
								<th class="col-md-1">Production Date</th>
								<th class="col-md-1">Pallet ID</th>
							</tr>
						</thead>
						<tbody>
							{% for item in entity.items %}
								<tr>
									<td class="text-right">{{ item.quantity|decimal }} <small class="text-muted">kg</small></td>
									<td class="text-right">{{ item.purchaseorderitem.totalReceived|decimal }}</td>
									<td class="text-right">{{ item.purchaseorderitem.getMaxQtyAllowedToReceive|decimal }}</td>
									<td>{{ item.mode }}</td>
									<td>{{ item.type }}</td>
									<td>{{ item.barcode }}</td>
									<td><a href="{{ path('product_show', { 'id' : item.product.id }) }}">{{ item.product.sku }} {{ item.product.name }}</a></td>
									<td>{{ item.lotNumber }}</td>
									<td>{{ utils.formatDate(item.productionDate) }}</td>
									<td>{{ item.palletId }}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6 col-xs-offset-1">
				{% if entity.memo %}
					<div class="well">
						<p>
							<strong>Memo</strong><br/>
							{{ entity.memo|nl2br }}
						</p>
					</div>
				{% endif %}
			</div>
		</div>

		{% include 'CIInventoryBundle:Misc:entityDateDetails.html.twig' with {'entity': entity } %}
	</div>

	<div class="col-sm-3">
		{% if is_expr_granted("hasAnyRole('ROLE_RECEIVEDORDER_FILE_DOWNLOAD')") %}
			<div class="row">
				<div class="panel panel-default custom-panel">
					<div class="panel-heading">
						<span class="panel-title">{{ FAIcon('paperclip', 'panel-title-icon') }}Attachments</span>
					</div>

					<div class="panel-body">
						<div class="panel-padding no-padding-vr">
						{% set imageExtensions = ['jpeg', 'jpg', 'png'] %}
						{% if entity.files|length > 0 %}
							{% for file in entity.files %}
								{% set fileName = file.name|split('.') %}
								<div class="item">
									<a href="{{ path('receiveorder_file_download', { 'id': file.id }) }}" class="thumbnail">
										{% if (fileName|last)|lower in imageExtensions %}
											<img src="{{ asset(file.webFilePath) | imagine_filter('image_thumbnail') }}" />
										{% else %}
											{{ file.name }}
										{% endif %}
									</a>
									<span class="item-text1">{{ file.name }}</span><br/>
									<span class="item-text2"></span>
								</div>
							{% endfor %}
						{% else %}
							<div class="item">
								No attachments yet.
							</div>
						{% endif %}
						</div>
					</div>
					{% if is_expr_granted("hasAnyRole('ROLE_RECEIVEDORDER_FILE_UPLOAD')") %}
						<div class="panel-footer">
							<a class="btn btn-primary btn-sm btn-block" href="{{ path('receiveorder_file', { 'id' :entity.id }) }}">{{ FAIcon('upload') }} Upload</a>
						</div>
					{% endif %}
				</div>
			</div>
		{% endif %}
		<div class="row">
			<div class="panel panel-default custom-panel">
				<div class="panel-heading">
					<span class="panel-title">{{ FAIcon('undo', 'panel-title-icon') }}Shipment Discrepancy Notice Status</span>
				</div> <!-- / .panel-heading -->
				<div class="panel-body">
					<div class="panel-padding no-padding-vr">
						{% if entity.purchaseReturns|length == 0 %}
							<div class="item">
								<span>
									There are no shipment discrepancy notices found for this receive order.
								</span>
							</div>
						{% endif %}

						{% for pr in entity.purchaseReturns %}
							<div class="item">
								{{ pr|renderStatusTag('item-status') }}
								<a class="item-link" href="{{ path('purchasereturn_show', { 'id' : pr.id }) }}">{{ utils.formatDate(pr.returnDate) }}</a>
								<span class="small">{{ pr.id }}</span><br/>
								<span class="item-text2">{{ pr.actionTaken|nl2br }}</span>
							</div>
						{% endfor %}
					</div>
				</div> <!-- / .panel-body -->

				{% if entity.active %}
				<div class="panel-footer">
					{% if is_expr_granted("hasAnyRole('ROLE_PURCHASERETURN_CREATE')") %}
						<a class="btn btn-primary btn-sm btn-block" href="{{ path('purchasereturn_new', { 'receiveOrderId' : entity.id }) }}">{{ FAIcon('plus') }} Add New</a>			
					{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="panel panel-default custom-panel">
				<div class="panel-heading">
					<span class="panel-title">{{ FAIcon('archive', 'panel-title-icon') }}Put Away Status</span>
				</div> <!-- / .panel-heading -->
				<div class="panel-body">
					<div class="panel-padding no-padding-vr">
						{% if hasPutAway %}
							<div class="item">
								{% set totalPct = ((entity.qtyPutAway / entity.qtyReceived) *100)|number_format(2, '.', '') %}
								<span class="item-text2">Total Put Away:</span>
								<span class="pull-right">
									<small>{{ totalPct|number_format(2) }}%</small>
									{% if totalPct >= 100 %}
										<span class="text-success">{{ FAIcon('check-circle') }}</span>
									{% endif %}
								</span>
								<div class="progress progress-striped" title="{{ totalPct }}%"><div class="progress-bar progress-bar-success" style="width: {{ totalPct }}%;"></div></div>
								<span class="item-text1">{{ entity.qtyPutAway|number_format(3) }} / {{  entity.qtyReceived|number_format(3) }}</span>
							</div>
						{% else %}
							<div class="item">
								<span>
									{% if entity.active %}
										There are no put aways found for this receive order.
									{% else %}
										Approve this receive order to start putting the items in the designated storage locations in the warehouse.
									{% endif %}
								</span>
							</div>
						{% endif %}

						{% for putAway in entity.putAways %}
							<div class="item">
								 {{ putAway|renderStatusTag('item-status') }}
								<a class="item-link" href="{{ path('putaway_show', { 'id' : putAway.id }) }}">{{ utils.formatDate(putAway.date) }}</a>
								<span class="small">{{ putAway.id }}</span>
								{% for item in putAway.items %}
									<br/><span class="item-text2">{{ item.palletId }} - {{ item.storageLocation.fullLocation }}</span>
								{% endfor %}
							</div>
						{% endfor %}
					</div>
				</div> <!-- / .panel-body -->

				{% if entity.active %}
				<div class="panel-footer">
					{% if is_expr_granted("hasAnyRole('ROLE_PUTAWAY_CREATE')") %}
						<a class="btn btn-primary btn-sm btn-block" href="{{ path('putaway_new', { 'transactionId' : entity.id, 'type' : constant('CI\\InventoryBundle\\Entity\\PutAway::TYPE_RECEIVE_ORDER') }) }}">{{ FAIcon('plus') }} Add New</a>			
					{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}