src/CI/InventoryBundle/Entity/Backload.php
<?php

namespace CI\InventoryBundle\Entity;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * Backload
 *
 * @ORM\Table(name="backload")
 * @ORM\Entity(repositoryClass="CI\InventoryBundle\Entity\BackloadRepository")
 * @Assert\Callback(methods={"validate"})
 * @ORM\HasLifecycleCallbacks()
 */
class Backload extends BaseEntity
{
	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="date", type="date")
	 * @Assert\NotBlank(message="Date must not be blank.")
	 * @Assert\Date()
	 */
	private $date;

	/**
	 * @ORM\Column(name="for_put_away", type="boolean")
	 */
	private $forPutAway;

	/**
	 * @ORM\ManyToOne(targetEntity="Shipping", inversedBy="backloads")
	 */
	private $shipping;

	/**
	 * @ORM\OneToMany(targetEntity="BackloadItem", mappedBy="backload", cascade={"persist", "remove"})
	 * @Assert\Valid
	 */
	private $items;

	/**
	 * @ORM\OneToMany(targetEntity="PutAway", mappedBy="backload", cascade={"persist", "remove"})
	 */
	private $putAways;

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->date = new \DateTime();
		$this->forPutAway = false;
		$this->items = new \Doctrine\Common\Collections\ArrayCollection();
		$this->putAways = new \Doctrine\Common\Collections\ArrayCollection();
	}

	/**
	 * Set date
	 *
	 * @param \DateTime $date
	 * @return Backload
	 */
	public function setDate($date)
	{
		$this->date = $date;
	
		return $this;
	}

	/**
	 * Get date
	 *
	 * @return \DateTime 
	 */
	public function getDate()
	{
		return $this->date;
	}

	/**
	 * Set forPutAway
	 *
	 * @param boolean $forPutAway
	 * @return Backload
	 */
	public function setForPutAway($forPutAway)
	{
		$this->forPutAway = $forPutAway;
	
		return $this;
	}

	/**
	 * Get forPutAway
	 *
	 * @return boolean 
	 */
	public function getForPutAway()
	{
		return $this->forPutAway;
	}

	/**
	 * Set shipping
	 *
	 * @param \CI\InventoryBundle\Entity\Shipping $shipping
	 * @return Backload
	 */
	public function setShipping(\CI\InventoryBundle\Entity\Shipping $shipping = null)
	{
		$this->shipping = $shipping;
	
		return $this;
	}

	/**
	 * Get shipping
	 *
	 * @return \CI\InventoryBundle\Entity\Shipping 
	 */
	public function getShipping()
	{
		return $this->shipping;
	}

	public function setItems(\Doctrine\Common\Collections\Collection $items)
	{
		foreach ($items as $item) {
			$item->setBackload($this);
		}
		
		$this->items = $items;
	}

	/**
	 * Get items
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getItems()
	{
		return $this->items;
	}

	/**
	 * Get putAways
	 *
	 * @return \Doctrine\Common\Collections\Collection 
	 */
	public function getPutAways()
	{
		return $this->putAways;
	}

	public function validate(ExecutionContextInterface $context)
	{
		$items = $this->getItems()->matching(Criteria::create()->where(Criteria::expr()->eq('isIncluded', true)));

		if ($items->count() == 0) {
			$context->addViolation('Please select at least one item.');
		}
	}

	public function checkForPutAway()
	{
		if ($this->getForPutAway()) {
			return false;
		} else {
			foreach ($this->getItems() as $item) {
				if (is_null($item->getPalletId())) {
					return false;
				}
			}

			return true;
		}
	}

	public function getActivePutAways()
	{
		$putAways = $this->getPutAways()->filter(function($putAway) { return $putAway->isActive(); });

		return $putAways;
	}

	public function isEditable()
	{
		return !$this->getForPutAway() && $this->getActive();
	}

	public function isDeletable()
	{
		return !$this->getForPutAway();
	}

	public function getLog()
	{
		return array(
			'Delivery #' => $this->getShipping()->getId(),
			'Date' => $this->getDate(),
			'For Put Away' => $this->getForPutAway() ? 'Yes' : 'No',
		);
	}
}

src/CI/InventoryBundle/Form/Type/BackloadType.php
<?php

namespace CI\InventoryBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use CI\InventoryBundle\Entity\Shipping;

class BackloadType extends AbstractType
{
	protected $em;

	public function __construct($em)
	{
		$this->em = $em;
	}

	/**
	 * @param FormBuilderInterface $builder
	 * @param array $options
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$em = $this->em;

		$builder
			->add('date', 'date', array(
				'label' => 'Date',
				'widget' => 'single_text',
				'format' => 'MM/dd/y',
				'attr' => array(
					'widget_col' => 4,
					'datepicker' => true,
					'input_group' => array('append' => 'calendar'),
				),
			))
			->add('shipping', 'entity_hidden', array(
				'required' => true,
				'class' => 'CIInventoryBundle:Shipping',
				'label' => 'Delivery #',
			))
			->add('items', 'collection', array(
				'type' => new BackloadItemType($em),
				'allow_add' => true,
				'allow_delete' => true,
				'by_reference' => false,
				'error_bubbling' => true,
				'prototype_name' => 'ANGLR_key_ANGLR',
			))
			->add('save', 'submit', array(
				'label' => 'Save ',
				'attr' => array(
					'class' => 'btn btn-success submit-button',
					'data-loading-text' => "Saving...",
				),
			))
		;
	}
	
	/**
	 * @param OptionsResolverInterface $resolver
	 */
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'CI\InventoryBundle\Entity\Backload'
		));
	}

	/**
	 * @return string
	 */
	public function getName()
	{
		return 'ci_inventorybundle_backload';
	}
}

src/CI/InventoryBundle/Controller/BackloadController.php
<?php

namespace CI\InventoryBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;

use CI\InventoryBundle\Entity\Backload;
use CI\InventoryBundle\Form\Type\BackloadType;
use CI\InventoryBundle\Model\BackloadModel as Model;

/**
 * Backload controller.
 *
 * @Route("/backload")
 */
class BackloadController extends BaseController
{
	const LINK_SHOW = 'backload_show';

	public function getModel()
	{
		return $this->get('ci.backload.model');
	}

	/**
	 * Lists all Backload entities.
	 *
	 * @Route("/", name="backload")
	 * @Method("GET")
	 * @Template()
	 * @Secure(roles="ROLE_BACKLOAD_LIST")
	 */
	public function indexAction(Request $request)
	{
		$model = $this->getModel();
		$form = $model->getFilterFormType();

		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				$params = $form->getData();
				$qb = $model->getIndex($params);
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please try again.');
			}
		}

		if (!isset($qb)) {
			$qb = $model->getIndex();
		}

		$paginator = $this->get('knp_paginator');
		$pagination = $paginator->paginate(
			$qb,
			$this->get('request')->query->get('page', 1),
			$this->container->getParameter('pagination_limit_per_page')
		);

		return array(
			'params' => isset($params) ? $params : null,
			'pagination' => isset($pagination) ? $pagination : null,
			'search_form' => $form->createView(),
		);
	}

	/**
	 * Creates a new Backload entity.
	 *
	 * @Route("/", name="backload_create")
	 * @Method("POST")
	 * @Template("CIInventoryBundle:Backload:new.html.twig")
	 * @Secure(roles="ROLE_BACKLOAD_CREATE")
	 */
	public function createAction(Request $request)
	{
		$model = $this->getModel();
		$entity = $model->getNewEntity();
		$form = $model->getFormType($entity);

		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				try {
					$model->saveEntity($form, $entity);
					$this->get('session')->getFlashBag()->add('success', $model->getMessages(Model::ACTION_CREATE));
					return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
				} catch (\Exception $e) {
					$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
				}
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
			}
		}

		return array(
			'entity' => $entity,
			'form' => $form->createView(),
		);
	}

	/**
	 * Displays a form to create a new Backload entity.
	 *
	 * @Route("/new/{shippingId}", name="backload_new")
	 * @Method("GET")
	 * @Template()
	 * @Secure(roles="ROLE_BACKLOAD_CREATE")
	 */
	public function newAction($shippingId)
	{
		$model = $this->getModel();
		$entity = $model->getNewEntity();
		$model->setEntityData($entity, $shippingId);
		$form = $model->getFormType($entity);

		return array(
			'entity' => $entity,
			'form'   => $form->createView(),
		);
	}

	/**
	 * Finds and displays a Backload entity.
	 *
	 * @Route("/{id}/show", name="backload_show")
	 * @Method("GET")
	 * @Template()
	 * @Secure(roles="ROLE_BACKLOAD_READ")
	 */
	public function showAction($id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);

		return array(
			'entity' => $entity,
		);
	}

	/**
	 * Displays a form to edit an existing Backload entity.
	 *
	 * @Route("/{id}/edit", name="backload_edit")
	 * @Method("GET")
	 * @Template()
	 * @Secure(roles="ROLE_BACKLOAD_UPDATE")
	 */
	public function editAction($id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);

		try {
			$model->isEditable($entity);
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
			return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $id)));
		}

		$model->setEntityData($entity);
		$editForm = $model->getFormType($entity);

		return array(
			'entity' => $entity,
			'edit_form' => $editForm->createView(),
		);
	}

	/**
	 * Edits an existing Backload entity.
	 *
	 * @Route("/{id}", name="backload_update")
	 * @Method("PUT")
	 * @Template("CIInventoryBundle:Backload:edit.html.twig")
	 * @Secure(roles="ROLE_BACKLOAD_UPDATE")
	 */
	public function updateAction(Request $request, $id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);

		try {
			$model->isEditable($entity);
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
			return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $id)));
		}
		
		$editForm = $model->getFormType($entity);

		if ($editForm->handleRequest($request)->isSubmitted()) {
			if ($editForm->isValid()) {
				try {
					$model->saveEntity($editForm, $entity);
					$this->get('session')->getFlashBag()->add('success', $model->getMessages(Model::ACTION_UPDATE));
					return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
				} catch (\Exception $e) {
					$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
				}
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
			}
		}

		return array(
			'entity' => $entity,
			'edit_form' => $editForm->createView(),
		);
	}

	/**
	 *
	 * @Route("/{id}/for-put-away", name="backload_for_put_away")
	 * @Method("GET")
	 * @Secure(roles="ROLE_BACKLOAD_CHANGE_STATUS")
	 */
	public function forPutAwayAction($id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);

		try {
			$status = $model->forPutAway($entity);
			$this->get('session')->getFlashBag()->add('success', $model->getMessages(Model::ACTION_FOR_PUT_AWAY));
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
		}

		return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $id)));
	}

	/**
	 * Creates a delete form.
	 *
	 * @Route("/confirm-delete/{id}", name="backload_confirm_delete")
	 * @Method("GET")
	 * @Template("CIInventoryBundle:Misc:delete.html.twig")
	 * @Secure(roles="ROLE_BACKLOAD_DELETE")
	 */
	public function confirmDeleteAction(Request $request, $id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);
		$deleteForm = $this->createDeleteForm($id);
	
		try {
			$model->isDeletable($entity);
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
			return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
		}
			
		return array(
			'entity' => $entity,
			'delete_form' => $deleteForm->createView(),
			'params' => $model->getDeleteParams($entity),
		);
	}
	
	/**
	 * Deletes a backload entity.
	 *
	 * @Route("/{id}", name="backload_delete")
	 * @Method("DELETE")
	 * @Secure(roles="ROLE_BACKLOAD_DELETE")
	 */
	public function deleteAction(Request $request, $id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);
		$form = $this->createDeleteForm($id);
	
		try {
			$model->isDeletable($entity);
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
			return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
		}
	
		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				try {
					$model->deleteEntity($id);
					$this->get('session')->getFlashBag()->add('success', $model->getMessages(Model::ACTION_DELETE));
				} catch (\Exception $e) {
					$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
				}
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Something went wrong. Please try again.');
			}
		}
	
		return $this->redirect($this->generateUrl('backload'));
	}

	 /**
	 * @Route("/status/{id}/{status}/change", name="backload_change_status")
	 * @Method("GET")
	 * @Secure(roles="ROLE_BACKLOAD_CHANGE_STATUS")
	 */
	public function changeStatusAction($id, $status)
	{
		try {
			$model = $this->getModel();
			$status = $model->changeStatus($id, $status);
			$this->get('session')->getFlashBag()->add('danger', $model->getMessages(Model::ACTION_CHANGE_STATUS));
		} catch (\Exception $e) {
			$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
		}

		return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $id)));
	}

	/**
	 * @Route("/revision/{id}", name="backload_revision")
	 * @Template("CIInventoryBundle:Log:index.html.twig")
	 * @Secure(roles="ROLE_BACKLOAD_READ")
	 */
	public function revisionAction($id)
	{
		$model = $this->getModel();
		$revision = $model->getRevision($id);

		return $this->entityRevision($revision['route'], $revision['name'], $revision['class']);
	}
	
	/**
	 * @Route("/revision/{parentId}/{id}/log", name="backload_log")
	 * @Template("CIInventoryBundle:Log:show.html.twig")
	 * @Secure(roles="ROLE_BACKLOAD_READ")
	 */
	public function logAction($parentId, $id)
	{
		$model = $this->getModel();
		$log = $model->getLog();

		return $this->entityLog($parentId, $log['route'], $id, $log['name'], $log['classes']);
	}
}

src/CI/InventoryBundle/Resources/views/Backload/edit.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIInventoryBundle:Backload:macro.html.twig' as macro %}

{% block breadcrumbs %}
	<li>Sales</li>
	<li><a href="{{ path('backload') }}">Backloads</a></li>
	<li><a href="{{ path('backload_show', { 'id' : entity.id }) }}">{{ entity.id }}</a></li>
	<li class="active">Edit</li>
{% endblock %}

{% block content %}
	<div class="page-header">
		<h1>{{ FAIcon('reply-all', 'page-header-icon') }} Backload # {{ entity.id }}</h1>
	</div>

	{% if form_errors(edit_form) is not empty %}
		{{ form_errors(edit_form) }}<br/>
	{% endif %}

	{{ form_start(edit_form, { 'action' : path('backload_update', { 'id' : entity.id }), 'method': 'PUT', 'attr': { 'class' : 'form-horizontal', 'novalidate' : 'novalidate', 'ng-controller' : 'BackloadController', 'ng-init' : 'init()' } }) }}
		{{ bootstrap_set_style('horizontal') }}
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group row">
								{{ form_label(edit_form.shipping) }}
								<div class="col-lg-8">
									{{ form_widget(edit_form.shipping) }}
									<p class="form-control-static"><a href="{{ path('shipping_show', { 'id' : entity.shipping.id }) }}">{{ entity.shipping.id }}</a></p>
								</div>
							</div>

							<div class="form-group row">
								<label class="control-label col-lg-4">Sales Order #</label>
								<div class="col-lg-8">
									<p class="form-control-static"><a href="{{ path('salesorder_show', { 'id' : entity.shipping.salesOrder.id }) }}">{{ entity.shipping.salesOrder.id }}</a></p>
								</div>
							</div>
						</div>

						<div class="col-sm-6">
							<div class="form-group row">
								<label class="control-label col-lg-4">Customer</label>
								<div class="col-lg-8">
									<p class="form-control-static"><a href="{{ path('customer_show', { 'id' : entity.shipping.salesOrder.customer.id }) }}">{{ entity.shipping.salesOrder.customer.name }}</a></p>
								</div>
							</div>
							{{ form_row(edit_form.date) }}
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive">
						<table class="table table-primary item-collection">
							<thead>
								<tr>
									<th></th>
									<th class="col-md-1 text-right">Quantity</th>
									<th class="col-md-2">Product</th>
									<th class="col-md-2">Lot Number</th>
									<th class="col-md-1">Production Date</th>
									<th class="col-md-2">Pallet ID <small>(optional)</small></th>
									<th class="col-md-2">Remarks <small>(optional)</small></th>
									<th class="col-md-2">Corrective Action <small>(optional)</small></th>
								</tr>
							</thead>
							<tbody>
								<tr ng-cloak ng-repeat="(key, item) in form.items" ng-class="{% verbatim %}{ success: item.isIncluded }{% endverbatim %}">
									{{ macro.item(edit_form.items.vars.prototype) }}
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<br/><br/>

			<div class="row">
				<div class="col-sm-12">
					<div class="form-actions">
						{{ form_widget(edit_form.save) }}
						<a href="{{ path('backload_show', { 'id' : entity.id }) }}" class="btn btn-default">Back</a>
					</div>
				</div>
			</div>
		{{ form_widget(edit_form._token) }}
	</form>
{% endblock %}

{% block javascripts %}
	{{ macro.initScript(edit_form) }}
	<script src="{{ asset('assets/js/angular/backload.js') }}"></script>
{% endblock %}

src/CI/InventoryBundle/Resources/views/Backload/show.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIInventoryBundle:Backload:macro.html.twig' as macro %}

{% block breadcrumbs %}
	<li>Sales</li>
	<li><a href="{{ path('backload') }}">Backloads</a></li>
	<li class="active">View</li>
{% endblock %}

{% block content %}
	<div class="page-header">
		<div class="row">
			<div class="col-sm-6">
				<h1>
					{{ FAIcon('reply-all', 'page-header-icon') }} Backload # {{ entity.id }}
				</h1>
				{% if entity.forPutAway and entity.active %}
					<span class="label label-success">For Put Away</span>
				{% elseif not entity.active %}
					<span class="label label-danger">Void</span>
				{% endif %}
			</div>

			<div class="col-sm-6">
				<div class="pull-right btn-toolbar">
					{% if entity.active %}
						{% if is_expr_granted("hasAnyRole('ROLE_BACKLOAD_CHANGE_STATUS')") and entity.activePutAways|length == 0 %}
							<a class="btn btn-outline btn-danger" href="{{ path("backload_change_status", {'id' : entity.id, 'status' : constant('CI\\InventoryBundle\\Entity\\Backload::STATUS_INACTIVE')}) }}">{{ FAIcon('warning') }} Void</a>
						{% endif %}
					{% else %}
						<a class="btn btn-outline btn-default disabled" href="#">{{ FAIcon('ban') }} Void</a>
					{% endif %}

					{% if entity.checkForPutAway %}
						<div class="btn-group">
							<a class="btn btn-outline btn-info" href="{{ path('backload_for_put_away', { 'id' : entity.id }) }}">{{ FAIcon('archive') }} Set as For Put Away</a>
						</div>
					{% endif %}

					{% if entity.isEditable %}
						<div class="btn-group btn-group-md">
							<a href="{{ path('backload_edit', { 'id': entity.id }) }}" class="btn btn-default">{{ FAIcon('pencil') }} Edit</a>
						</div>
					{% endif %}

					<div class="btn-group btn-group-md">
						<div class="btn-group">
							<a href="#" class="btn dropdown-toggle" data-toggle="dropdown">More {{ FAIcon('caret-down') }}</a>
							<ul class="dropdown-menu">
								<li><a href="{{ path('backload_revision', { 'id': entity.id }) }}">{{ FAIcon('info-circle') }} View Logs</a></li>
								{% if entity.isDeletable %}
									<li><a href="{{ path('backload_confirm_delete', { 'id': entity.id }) }}">{{ FAIcon('trash-o') }} Delete</a></li>
								{% endif %}
							</ul>
						</div>
						<div class="btn-group">
							<a class="btn btn-default" href="{{ path('backload') }}">{{ FAIcon('th-large') }} List All</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<table class="table table-no-border profile">
						<tr>
							<th class="col-xs-4">Delivery #</th>
							<td><a href="{{ path('shipping_show', { 'id' : entity.shipping.id }) }}">{{ entity.shipping.id }}</a></td>
						</tr>
						<tr>
							<th>Sales Order #</th>
							<td><a href="{{ path('salesorder_show', { 'id' : entity.shipping.salesOrder.id }) }}">{{ entity.shipping.salesOrder.id }}</a></td>
						</tr>
					</table>
				</div>
				<div class="col-md-6 col-xs-12">
					<table class="table table-no-border profile">
						<tr>
							<th class="col-xs-4">Customer</th>
							<td><a href="{{ path('customer_show', { 'id' : entity.shipping.salesOrder.customer.id }) }}">{{ entity.shipping.salesOrder.customer.name }}</a></td>
						</tr>
						<tr>
							<th>Date</th>
							<td>{{ utils.formatDate(entity.date) }}</td>
						</tr>
					</table>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="table-responsive">
						<table class="table table-light">
							<thead>
								<tr>
									<th class="col-md-1 text-right">Quantity</th>
									<th class="col-md-3">Product</th>
									<th class="col-md-1">Lot Number</th>
									<th class="col-md-2">Production Date</th>
									<th class="col-md-1">Pallet ID</th>
									<th class="col-md-2">Remarks</th>
									<th class="col-md-2">Corrective Action</th>
								</tr>
							</thead>
							<tbody>
								{% for item in entity.items %}
									<tr>
										<td class="text-right">{{ item.quantity|decimal(2) }}</td>
										<td>
											<a href="{{ path('product_show', { 'id' : item.shippingItem.salesOrderItem.quotation.product.id }) }}">
												{{ item.shippingItem.productName }}
											</a>
										</td>
										<td>{{ item.lotNumber }}</td>
										<td>{{ utils.formatDate(item.productionDate) }}</td>
										<td>{{ item.palletId }}</td>
										<td>{{ item.remarks|nl2br }}</td>
										<td>{{ item.correctiveAction|nl2br }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-3">
			<div class="row">
				<div class="panel panel-default custom-panel">
					<div class="panel-heading">
						<span class="panel-title">{{ FAIcon('archive', 'panel-title-icon') }}Put Away Status</span>
					</div> <!-- / .panel-heading -->
					<div class="panel-body">
						<div class="panel-padding no-padding-vr">
							{% if entity.putAways|length == 0 %}
								<div class="item">
									<span>
										There are no put aways found for this backload.
									</span>
								</div>
							{% endif %}
							
							{% for pa in entity.putAways %}
								<div class="item">
									<a class="item-link" href="{{ path('putaway_show', { 'id' : pa.id }) }}">{{ utils.formatDate(pa.date) }}</a> 
									<span class="small">{{ pa.id }}</span><br/>
								</div>
							{% endfor %}
						</div>
					</div> <!-- / .panel-body -->
					{% if entity.forPutAway and entity.active %}
						{% if not entity.activePutAways|length > 0 %}
							<div class="panel-footer">
								<a class="btn btn-primary btn-sm btn-block" href="{{ path('putaway_new', { 'transactionId' : entity.id, 'type' : constant('CI\\InventoryBundle\\Entity\\PutAway::TYPE_BACKLOAD') }) }}">{{ FAIcon('plus') }} Add New</a>
							</div>
						{% endif %}
						
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}